seed_everything: 42
trainer:
  accelerator: mps
  # accelerator: auto
  # devices: 1
  # precision: bf16-mixed # Enable mixed precision training
  precision: 32
  gradient_clip_val: 1.0
  accumulate_grad_batches: 3 # Critical for sequential multi-task training
  max_steps: 30000
  val_check_interval: 1500 # batches
  default_root_dir: exp
  log_every_n_steps: 1
  limit_val_batches: 300
  # enable_progress_bar: false
  # fast_dev_run: 3
  # num_sanity_val_steps: 3
  # profiler:
  #   class_path: lightning.pytorch.profilers.PyTorchProfiler
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: epoch{epoch:02d}-val_loss={val/loss/total:.2f}
        save_top_k: 3
        save_last: link
        monitor: val/loss/total
        mode: min
        auto_insert_metric_name: false
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: 3
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.DeviceStatsMonitor

model:
  num_tags: 8110
  num_artists: 1024
  num_characters: 2751
  backbone_variant: vit_base_patch16_224
  cls_token: false
  reg_tokens: 0
  image_size: 448
  tag_embed_dim: 512
  artist_embed_dim: 128
  character_embed_dim: 128
  dropout: 0.1
  loss_weights:
    tag: 1.0
    artist: 1.0
    character: 1.0
    quality: 1.0
    ortho: 1.0
  tag_contrastive_config:
    initial_temp: 0.05
    margin: 0.2
    central_weight: 1.5
  artist_contrastive_config:
    initial_temp: 0.1
    margin: 0.2
    central_weight: 1.5
  character_contrastive_config:
    initial_temp: 0.05
    margin: 0.2
    central_weight: 1.5
  base_lr: 3e-4
  backbone_lr: 3e-5
  lr_start_ratio: 0.1
  lr_end_ratio: 0.1
  warmup_percent: 0.05
  partial_unfreeze_percent: 0.15
  full_unfreeze_percent: 0.50
  partial_unfreeze_layers: 4
  tag_dict_path: ../danbooru2023/export/train/tag_indices_full.json
  artist_dict_path: ../danbooru2023/export/train/artist_indices.json
  character_dict_path: ../danbooru2023/export/train/character_indices_full.json

data:
  num_tags: 8110
  num_artists: 1024
  num_characters: 2751
  classes_per_batch: 4
  samples_per_class: 2
  num_workers: 0
  image_size: 448
  label_smoothing_eps: 0.1
  train_parquet_path: ../danbooru2023/export/train/images.parquet
  train_tar_dir: ../danbooru2023/export/train
  valid_parquet_path: ../danbooru2023/export/valid/images.parquet
  valid_tar_dir: ../danbooru2023/export/valid
  train_tag_dict_path: ../danbooru2023/export/train/tag_indices.json
  train_artist_dict_path: ../danbooru2023/export/train/artist_indices.json
  train_character_dict_path: ../danbooru2023/export/train/character_indices.json
