seed_everything: 42
trainer:
  accelerator: mps
  precision: 32
  val_check_interval: 50 # batches
  limit_val_batches: 100
  default_root_dir: exp
  log_every_n_steps: 1
  # fast_dev_run: 3
  # num_sanity_val_steps: 3
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "{step}"
        mode: min
        monitor: train/loss/total
        every_n_train_steps: 10
        save_weights_only: true
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: 5
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

model:
  tag_freq_path: ../danbooru2023/export/train/tag_freq.json
  artist_freq_path: ../danbooru2023/export/train/artist_freq.json
  character_freq_path: ../danbooru2023/export/train/character_freq.json

data:
  classes_per_batch: 4
  samples_per_class: 2
  num_workers: 0
  train_tar_dir: ../danbooru2023/export/train
  valid_tar_dir: ../danbooru2023/export/valid
  train_parquet_path: ../danbooru2023/export/train/images.parquet
  valid_parquet_path: ../danbooru2023/export/valid/images.parquet
  train_tag_dict_path: ../danbooru2023/export/train/tag_indices.json
  train_artist_dict_path: ../danbooru2023/export/train/artist_indices.json
  train_character_dict_path: ../danbooru2023/export/train/character_indices.json
