seed_everything: 42
trainer:
  accelerator: auto
  devices: 1
  precision: bf16-mixed # Enable mixed precision training
  gradient_clip_val: 1.0
  # accumulate_grad_batches: 3
  max_steps: 20000
  val_check_interval: 999 # batches
  check_val_every_n_epoch: null
  default_root_dir: /volume/exp
  log_every_n_steps: 1
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: step={step}-val_loss={val/loss/total:.2f}
        mode: min
        save_top_k: 3
        monitor: val/loss/total
        every_n_train_steps: 1000
        auto_insert_metric_name: false
        save_weights_only: true
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: 3
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

model:
  num_tags: 8110
  num_artists: 1024
  num_characters: 2751
  backbone_variant: vit_base_patch16_224
  cls_token: false
  reg_tokens: 0
  image_size: 448
  tag_embed_dim: 512
  artist_embed_dim: 128
  character_embed_dim: 128
  dropout: 0.1
  tasks: [tag, character, artist, quality]
  loss_weights:
    tag: 1.0
    artist: 1.0
    character: 1.0
    quality: 0.2
    ortho: 1.0
  temp_strategy: fixed
  tag_contrastive_config:
    temp: 0.05
    margin: 0.1
    central_weight: 1.5
  artist_contrastive_config:
    temp: 0.1
    margin: 0.0
    central_weight: 1.0
  character_contrastive_config:
    temp: 0.1
    margin: 0.0
    central_weight: 1.0
  base_lr: 1e-4
  backbone_lr: 1e-5
  lr_start_ratio: 0.1
  lr_end_ratio: 0.1
  warmup_percent: 0.1
  # unfreeze_schedule:
  tag_dict_path: ../danbooru2023/train/tag_indices_full.json
  artist_dict_path: ../danbooru2023/train/artist_indices.json
  character_dict_path: ../danbooru2023/train/character_indices_full.json

data:
  num_tags: 8110
  num_artists: 1024
  num_characters: 2751
  classes_per_batch: 32
  samples_per_class: 4
  num_workers: 32
  image_size: 448
  label_smoothing_eps: 0.1
  data_tasks: [tag, character, artist]
  sample_cutoff: 24
  task_probs:
    tag: 0.4
    artist: 0.4
    character: 0.2
  train_parquet_path: ../danbooru2023/train/images.parquet
  train_tar_dir: ../danbooru2023/train
  valid_parquet_path: ../danbooru2023/valid/images.parquet
  valid_tar_dir: ../danbooru2023/valid
  train_tag_dict_path: ../danbooru2023/train/tag_indices.json
  train_artist_dict_path: ../danbooru2023/train/artist_indices.json
  train_character_dict_path: ../danbooru2023/train/character_indices.json
