seed_everything: 42
trainer:
  accelerator: auto
  devices: 1
  precision: bf16-mixed # Enable mixed precision training
  gradient_clip_val: 1.0
  accumulate_grad_batches: 4
  max_steps: 10000
  val_check_interval: 499 # batches
  check_val_every_n_epoch: null
  default_root_dir: exp
  log_every_n_steps: 10
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: step={step}-val_loss={val/loss/total:.2f}
        mode: min
        save_top_k: 3
        monitor: val/loss/total
        every_n_train_steps: 500
        auto_insert_metric_name: false
        save_weights_only: true
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: 5
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

model:
  num_tags: 8110
  num_artists: 1024
  num_characters: 2751
  backbone_variant: vit_base_patch16_224
  cls_token: false
  reg_tokens: 0
  image_size: 448
  tag_embed_dim: 768
  artist_embed_dim: 256
  character_embed_dim: 256
  skip_head: true
  dropout: 0.0
  tasks: [tag]
  copy_wd_weights: true
  use_pretrained_backbone: false
  use_lora: true
  lora_config:
    r: 16
    lora_alpha: 32
    lora_dropout: 0.1
    bias: lora_only
    target_modules: [attn.qkv, attn.proj, mlp.fc1, mlp.fc2]
    layers_to_transform: [8, 9, 10, 11]
  loss_weights:
    tag: 1.0
    artist: 1.0
    character: 1.0
    quality: 1.0
  use_focal_loss: false
  class_reweighting: false
  class_reweighting_method: log
  temp_strategy: class
  tag_contrastive_config:
    min_temp: 0.05
    max_temp: 0.2
    min_margin: 0.1
    max_margin: 0.3
    central_weight: 0.0
    # negative_percent: 0.1
  artist_contrastive_config:
    temp: 0.06
    margin: 0.2
    central_weight: 0.0
  character_contrastive_config:
    temp: 0.06
    margin: 0.2
    central_weight: 0.0
  base_lr: 1e-3
  lr_start_ratio: 0.1
  lr_end_ratio: 0.1
  warmup_percent: 0.1
  tag_freq_path: ../danbooru2023/train-400k/tag_freq.json
  artist_freq_path: ../danbooru2023/train-400k/artist_freq.json
  character_freq_path: ../danbooru2023/train-400k/character_freq.json

data:
  num_tags: 8110
  num_artists: 1024
  num_characters: 2751
  classes_per_batch: 32
  samples_per_class: 4
  num_workers: 32
  image_size: 448
  label_smoothing_eps: 0.0
  data_tasks: [tag]
  sample_cutoff: 192
  train_tar_dir: ../danbooru2023/train
  valid_tar_dir: ../danbooru2023/valid
  train_parquet_path: ../danbooru2023/train-400k/images.parquet
  valid_parquet_path: ../danbooru2023/valid/images.parquet
  train_tag_dict_path: ../danbooru2023/train-400k/tag_indices.json
  train_artist_dict_path: ../danbooru2023/train-400k/artist_indices.json
  train_character_dict_path: ../danbooru2023/train-400k/character_indices.json
